"""created tables

Revision ID: 0c0dd4674c0a
Revises: 
Create Date: 2023-09-07 16:08:36.122812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0dd4674c0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('nfl_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fantasy_data_id', sa.Integer(), nullable=True),
    sa.Column('espn_id', sa.String(), nullable=True),
    sa.Column('stats_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height', sa.String(), nullable=True),
    sa.Column('weight', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('college', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('search_rank', sa.Integer(), nullable=True),
    sa.Column('depth_chart_position', sa.Integer(), nullable=True),
    sa.Column('years_exp', sa.Integer(), nullable=True),
    sa.Column('injury_status', sa.String(), nullable=True),
    sa.Column('hashtag', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('fantasy_teams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_fantasy_teams_user_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('league_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_league_members_league_id_leagues')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_league_members_user_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('nfl_player_fantasy_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nfl_player_id', sa.Integer(), nullable=True),
    sa.Column('fantasy_position', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['nfl_player_id'], ['nfl_players.id'], name=op.f('fk_nfl_player_fantasy_positions_nfl_player_id_nfl_players')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_posts_user_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_comments_post_id_posts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comments_user_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('fantasy_players',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('fantasy_team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_teams.id'], name=op.f('fk_fantasy_players_fantasy_team_id_fantasy_teams')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('player_performances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('fantasy_player_id', sa.Integer(), nullable=True),
    sa.Column('opponent_player_id', sa.Integer(), nullable=True),
    sa.Column('week_num', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.String(), nullable=True),
    sa.Column('ppr_points', sa.Float(), nullable=True),
    sa.Column('standard_points', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fantasy_player_id'], ['fantasy_players.id'], name=op.f('fk_player_performances_fantasy_player_id_fantasy_players')),
    sa.ForeignKeyConstraint(['opponent_player_id'], ['fantasy_players.id'], name=op.f('fk_player_performances_opponent_player_id_fantasy_players')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_performances')
    op.drop_table('fantasy_players')
    op.drop_table('comments')
    op.drop_table('posts')
    op.drop_table('nfl_player_fantasy_positions')
    op.drop_table('league_members')
    op.drop_table('fantasy_teams')
    op.drop_table('users')
    op.drop_table('nfl_players')
    op.drop_table('leagues')
    # ### end Alembic commands ###
