"""updated table nfl_player

Revision ID: 1f1fcc27495d
Revises: 50772f7e0b8b
Create Date: 2023-09-07 16:28:09.794296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1fcc27495d'
down_revision = '50772f7e0b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfl_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfl_players', schema=None) as batch_op:
        batch_op.drop_column('player_id')

    # ### end Alembic commands ###
