"""updated table nfl_players

Revision ID: 50772f7e0b8b
Revises: 0c0dd4674c0a
Create Date: 2023-09-07 16:16:27.503750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50772f7e0b8b'
down_revision = '0c0dd4674c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfl_players', schema=None) as batch_op:
        batch_op.drop_column('search_rank')
        batch_op.drop_column('depth_chart_position')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfl_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('depth_chart_position', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('search_rank', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
