"""removed opponent id from player_performance table

Revision ID: 6d6e4a2ec884
Revises: 6e45207f270e
Create Date: 2023-09-18 12:23:46.579081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6e4a2ec884'
down_revision = '6e45207f270e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfl_players', schema=None) as batch_op:
        batch_op.drop_index('ix_nfl_players_first_name')
        batch_op.create_index(batch_op.f('ix_nfl_players_first_name'), ['first_name'], unique=False)

    with op.batch_alter_table('player_performances', schema=None) as batch_op:
        batch_op.drop_constraint('fk_player_performances_opponent_player_id_fantasy_players', type_='foreignkey')
        batch_op.drop_column('opponent_player_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_performances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opponent_player_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_player_performances_opponent_player_id_fantasy_players', 'fantasy_players', ['opponent_player_id'], ['id'])

    with op.batch_alter_table('nfl_players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nfl_players_first_name'))
        batch_op.create_index('ix_nfl_players_first_name', ['first_name'], unique=False)

    # ### end Alembic commands ###
