"""updated players id to match the NFL table

Revision ID: a0b49d1f62e9
Revises: e893b43bf271
Create Date: 2023-09-13 10:37:05.276852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b49d1f62e9'
down_revision = 'e893b43bf271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fantasy_players', schema=None) as batch_op:
        batch_op.alter_column('nfl_player_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('nfl_players', schema=None) as batch_op:
        batch_op.drop_index('ix_nfl_players_first_name')
        batch_op.create_index(batch_op.f('ix_nfl_players_last_name'), ['last_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfl_players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nfl_players_last_name'))
        batch_op.create_index('ix_nfl_players_first_name', ['first_name'], unique=False)

    with op.batch_alter_table('fantasy_players', schema=None) as batch_op:
        batch_op.alter_column('nfl_player_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
