"""updated models

Revision ID: f694e89de1ec
Revises: d1104fef3e2c
Create Date: 2023-09-14 14:21:19.210735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f694e89de1ec'
down_revision = 'd1104fef3e2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfl_players', schema=None) as batch_op:
        batch_op.drop_index('ix_nfl_players_first_name')
        batch_op.create_index(batch_op.f('ix_nfl_players_last_name'), ['last_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfl_players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nfl_players_last_name'))
        batch_op.create_index('ix_nfl_players_first_name', ['first_name'], unique=False)

    # ### end Alembic commands ###
